### ISSUE TITLE
Error Applying Less Grind

### ISSUE THREAD

**Issue by ggoodrich2015** [Donovan522/donovan-7d2d-modlets#57]
![image](https://github.com/DonovanMods/donovan-7d2d-modlets/assets/43646139/3e0b4681-6669-48f0-af3b-cf6310e0e414)

Sorry for not giving context, just trying to help out, but don't want to dig into that much.

**Comment by dyoung522** [comment]
Thanks for letting me know... which version are you using and do you have any other mods installed?

I ask because those errors seem to indicate that this may be a conflict with another mod or possibly an older version of `donovan-lessgrind`

**Comment by ggoodrich2015** [comment]
I'm using the most recent version of all mods and this is the list.

1. [Mod Manager](https://7daystodiemods.com/mod-manager/)
2. [Add Sewing Kit](https://7daystodiemods.com/add-sewing-kit/)
3. [Big Backpack - Donovan](https://7daystodiemods.com/big-backpack/)
4. [Better Collectors - Donovan](
https://7daystodiemods.com/better-collectors/)
5. [Better Dyes - Donovan](https://7daystodiemods.com/better-dyes/)
6. [Craftable Parts - Donovan](
https://7daystodiemods.com/donovan-craftable-parts/)
7. [More Books - Donovan](https://7daystodiemods.com/more-books/)
8. [More Perks - Donovan](https://7daystodiemods.com/more-perks/)
9. [Stop Fuel Waste](https://www.nexusmods.com/7daystodie/mods/1884)
10. [Faster Walk and Run Speed](
https://7daystodiemods.com/faster-faster-walk-and-run-speed/)
11. [HUD Plus 1.8.0](https://7daystodiemods.com/agf-hudplus/)

My best guess would be a conflict with the stop fuel waste mod.

**Comment by dyoung522** [comment]
I also use Stop Fuel Waste with my modlets, so I don't think that is the conflict.

The error is coming from `donovan-lessgrind` and I suspect it may be conflicting with `donovan-bettercollectors` (which loads first). If so, it's safe to ignore that error because `donovan-bettercollectors` is already doing what you want, but I'll investigate that further.

However, either way, I highly recommend you download and install the latest release of my mods directly from here instead of from 7daystodiemods.com because that site lags a bit behind on releases.

[Here's a direct link to the latest releases](https://github.com/DonovanMods/donovan-7d2d-modlets/releases)

**Comment by ggoodrich2015** [comment]
Thanks for the information,

I love 7daystodiemods.com as it seems to have better quality on it. I
really wish there was a search feature with filters though to allow you to
search by most liked and game version.

Have a good one,
Garrett.
